name: Deploy Quartz site to GitHub Pages
 
on:
  workflow_dispatch:
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      # Update references
      - name: Git Submodule Update
        run: | 
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build --directory notes/notes
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4